
DROP TABLE MYMVCBOARD;
DROP SEQUENCE MYMVCBOARDSEQ;

CREATE SEQUENCE MYMVCBOARDSEQ;
--시퀀스 번호, 작성자, 제목, 내용, 작성일
CREATE TABLE MYMVCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(200) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO MYMVCBOARD
VALUES(MYMVCBOARDSEQ.NEXTVAL, '관리자', '테스트', '테스트중입니다 123', '17/10/26');

SELECT * FROM MYMVCBOARD;